Repository PrograMemo-Groom/TeamMemoFlow, pull requests merged in 2025-01, with the labels that each got.

#53 ✨ 초기 세팅 - STORE 추가
  package-lock.json
  package.json
  src/App.jsx
  src/App.module.scss
  src/index.js
  src/store/slice/CommonSlice.js
Labels: 기능추가, 기본 설정

#58 ✨ Setting 페이지 ui 구현
  src/App.jsx
  src/pages/setting/Setting.jsx
  src/pages/setting/Setting.module.scss
  src/pages/setting/SettingPage.jsx
  src/pages/setting/components/Account.jsx
  src/pages/setting/components/Account.module.scss
  src/pages/setting/components/Profile.jsx
  src/pages/setting/components/Profile.module.scss
  src/pages/setting/components/Social.jsx
  src/pages/setting/components/Social.module.scss
  src/styles/_mixins.scss
  src/styles/_variables.scss
Labels: UI/UX

#63 ✨로그인 및 회원가입 페이지 연동
  src/App.jsx
  src/App.module.scss
  src/constants/ValidateTypes.js
  src/pages/user/FindAccount.jsx
  src/pages/user/FindAccount.module.scss
  src/pages/user/Join.jsx
  src/pages/user/Join.module.scss
  src/pages/user/Login.js
  src/pages/user/Login.jsx
  src/pages/user/Login.module.scss
  src/pages/user/components/FormInput.jsx
  src/pages/user/components/ValidateLabel.jsx
  src/store/Store.js
  src/store/slice/CommonSlice.js
  src/store/slice/UserSlice.js
  src/styles/_mixins.scss
  src/styles/_variables.scss
  src/utils/Validate.js
Labels: UI/UX, 데이터 처리
